# Generated by Django 3.2.4 on 2021-06-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0002_patient_patientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patientUser',
        ),
    ]
