# Generated by Django 3.2.4 on 2021-06-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0006_patient_emergencycontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergencyContact',
            new_name='patientBirthDate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patientEmail',
            new_name='patientEmergencyContact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patientPassword',
            new_name='patientEmergencyContact2',
        ),
        migrations.AddField(
            model_name='patient',
            name='patientEmergencyContact3',
            field=models.CharField(default='', max_length=30),
        ),
    ]
