# Generated by Django 3.2.4 on 2021-06-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0007_auto_20210624_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientEmergencyContactName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientEmergencyContactName2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientEmergencyContactName3',
            field=models.CharField(default='', max_length=30),
        ),
    ]
