# Generated by Django 3.2.4 on 2021-06-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0011_auto_20210629_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patientEmergencyContactName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patientEmergencyContactName2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patientEmergencyContactName3',
        ),
    ]
