# Generated by Django 3.2.4 on 2021-06-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0012_auto_20210629_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_patient',
            field=models.CharField(default='Untitled', max_length=30),
        ),
    ]
