# Generated by Django 3.2.4 on 2021-06-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0013_alter_requests_request_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientEmergencyContact',
            field=models.CharField(default='besieged', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientEmergencyContact2',
            field=models.CharField(default='besieged', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientEmergencyContact3',
            field=models.CharField(default='besieged', max_length=30),
        ),
    ]
