# Generated by Django 3.2.4 on 2021-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0015_auto_20210630_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='listedPatients2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='listedPatients3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='listedPatients4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='listedPatients5',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='listedPatients6',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='listedPatients',
            field=models.CharField(default='', max_length=30),
        ),
    ]
