# Generated by Django 3.2.4 on 2021-06-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0008_auto_20210624_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='caretakerEmail',
        ),
    ]
