# Generated by Django 3.2.4 on 2021-07-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0016_auto_20210630_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='request_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
