# Generated by Django 3.2.4 on 2021-06-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
