# Generated by Django 3.2.4 on 2021-06-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapSpeech_app', '0003_remove_patient_patientuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patientName',
            new_name='patientFullName',
        ),
        migrations.RemoveField(
            model_name='caretaker',
            name='caretakerUser',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='caretakerEmail',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='caretakerFullName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='caretakerPassword',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientEmail',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientPassword',
            field=models.CharField(default='', max_length=30),
        ),
    ]
